//! The language registry: every language the code tools can outline, its
//! tree-sitter grammar, and its display/import metadata.

use std::path::Path;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum LangId {
    Rust,
    TypeScript,
    Tsx,
    Python,
    Go,
    Java,
    C,
    Cpp,
    Ruby,
    Lua,
    Bash,
    Kotlin,
    Swift,
    CSharp,
    Elixir,
    Scala,
    Php,
    Html,
    Gleam,
    Dart,
    Starlark,
    Nix,
    Zig,
    Markdown,
    Css,
    Fish,
    Gdscript,
    Gdshader,
    GodotResource,
    ObjC,
    Perl,
    SvelteNext,
    Zsh,
    Sql,
    Yaml,
    Toml,
}

impl LangId {
    pub fn from_path(p: &Path) -> Option<Self> {
        let ext = p.extension().and_then(|e| e.to_str())?;
        Self::from_extension(ext)
    }

    pub fn from_extension(ext: &str) -> Option<Self> {
        match ext {
            "rs" => Some(Self::Rust),
            "ts" => Some(Self::TypeScript),
            "tsx" | "jsx" => Some(Self::Tsx),
            "js" | "mjs" | "cjs" => Some(Self::TypeScript),
            "py" | "pyi" => Some(Self::Python),
            "go" => Some(Self::Go),
            "java" => Some(Self::Java),
            "c" | "h" => Some(Self::C),
            "cpp" | "cc" | "cxx" | "hpp" | "hh" | "hxx" | "ixx" => Some(Self::Cpp),
            "rb" => Some(Self::Ruby),
            "lua" => Some(Self::Lua),
            "sh" | "bash" => Some(Self::Bash),
            "kt" | "kts" => Some(Self::Kotlin),
            "swift" => Some(Self::Swift),
            "cs" => Some(Self::CSharp),
            "ex" | "exs" => Some(Self::Elixir),
            "scala" => Some(Self::Scala),
            "php" => Some(Self::Php),
            "html" | "htm" => Some(Self::Html),
            "gleam" => Some(Self::Gleam),
            "dart" => Some(Self::Dart),
            "bzl" | "bazel" | "build" => Some(Self::Starlark),
            "nix" => Some(Self::Nix),
            "zig" => Some(Self::Zig),
            "md" | "mdx" => Some(Self::Markdown),
            "css" => Some(Self::Css),
            "fish" => Some(Self::Fish),
            "gd" => Some(Self::Gdscript),
            "gdshader" => Some(Self::Gdshader),
            "tscn" | "tres" => Some(Self::GodotResource),
            "objc" => Some(Self::ObjC),
            "perl" => Some(Self::Perl),
            "svelte-next" => Some(Self::SvelteNext),
            "zsh" => Some(Self::Zsh),
            "sql" => Some(Self::Sql),
            "yaml" | "yml" => Some(Self::Yaml),
            "toml" => Some(Self::Toml),
            _ => None,
        }
    }

    pub fn ts_language(&self) -> tree_sitter::Language {
        match self {
            Self::Rust => tree_sitter_rust::LANGUAGE.into(),
            Self::TypeScript => tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into(),
            Self::Tsx => tree_sitter_typescript::LANGUAGE_TSX.into(),
            Self::Python => tree_sitter_python::LANGUAGE.into(),
            Self::Go => tree_sitter_go::LANGUAGE.into(),
            Self::Java => tree_sitter_java::LANGUAGE.into(),
            Self::C => tree_sitter_c::LANGUAGE.into(),
            Self::Cpp => tree_sitter_cpp::LANGUAGE.into(),
            Self::Ruby => tree_sitter_ruby::LANGUAGE.into(),
            Self::Lua => tree_sitter_lua::LANGUAGE.into(),
            Self::Bash => tree_sitter_bash::LANGUAGE.into(),
            Self::Kotlin => tree_sitter_kotlin_ng::LANGUAGE.into(),
            Self::Swift => tree_sitter_swift::LANGUAGE.into(),
            Self::CSharp => tree_sitter_c_sharp::LANGUAGE.into(),
            Self::Elixir => tree_sitter_elixir::LANGUAGE.into(),
            Self::Scala => tree_sitter_scala::LANGUAGE.into(),
            Self::Php => tree_sitter_php::LANGUAGE_PHP.into(),
            Self::Html => tree_sitter_html::LANGUAGE.into(),
            Self::Gleam => tree_sitter_gleam::LANGUAGE.into(),
            Self::Dart => tree_sitter_dart::LANGUAGE.into(),
            Self::Starlark => tree_sitter_starlark::LANGUAGE.into(),
            Self::Nix => tree_sitter_nix::LANGUAGE.into(),
            Self::Zig => tree_sitter_zig::LANGUAGE.into(),
            Self::Markdown => tree_sitter_md::LANGUAGE.into(),
            Self::Css => tree_sitter_css::LANGUAGE.into(),
            Self::Fish => tree_sitter_fish::language(),
            Self::Gdscript => tree_sitter_gdscript::LANGUAGE.into(),
            Self::Gdshader => tree_sitter_gdshader::LANGUAGE.into(),
            Self::GodotResource => tree_sitter_godot_resource::LANGUAGE.into(),
            Self::ObjC => tree_sitter_objc::LANGUAGE.into(),
            Self::Perl => tree_sitter_perl::LANGUAGE.into(),
            Self::SvelteNext => tree_sitter_svelte_next::LANGUAGE.into(),
            Self::Zsh => tree_sitter_zsh::LANGUAGE.into(),
            Self::Sql => tree_sitter_sequel::LANGUAGE.into(),
            Self::Yaml => tree_sitter_yaml::LANGUAGE.into(),
            Self::Toml => tree_sitter_toml_ng::LANGUAGE.into(),
        }
    }

    pub(crate) fn name(&self) -> &'static str {
        match self {
            Self::Rust => "rust",
            Self::TypeScript => "typescript",
            Self::Tsx => "tsx",
            Self::Python => "python",
            Self::Go => "go",
            Self::Java => "java",
            Self::C => "c",
            Self::Cpp => "cpp",
            Self::Ruby => "ruby",
            Self::Lua => "lua",
            Self::Bash => "bash",
            Self::Kotlin => "kotlin",
            Self::Swift => "swift",
            Self::CSharp => "csharp",
            Self::Elixir => "elixir",
            Self::Scala => "scala",
            Self::Php => "php",
            Self::Html => "html",
            Self::Gleam => "gleam",
            Self::Dart => "dart",
            Self::Starlark => "starlark",
            Self::Nix => "nix",
            Self::Zig => "zig",
            Self::Markdown => "markdown",
            Self::Css => "css",
            Self::Fish => "fish",
            Self::Gdscript => "gd",
            Self::Gdshader => "gdshader",
            Self::GodotResource => "godot-resource",
            Self::ObjC => "objc",
            Self::Perl => "perl",
            Self::SvelteNext => "svelte",
            Self::Zsh => "zsh",
            Self::Sql => "sql",
            Self::Yaml => "yaml",
            Self::Toml => "toml",
        }
    }

    pub fn import_separator(&self) -> &'static str {
        match self {
            Self::Rust => "::",
            Self::Python => ".",
            Self::Go => ".",
            Self::Ruby => "::",
            Self::Php => "\\",
            Self::CSharp => ".",
            Self::Dart => ".",
            Self::Starlark => ".",
            Self::Nix => ".",
            Self::Zig => ".",
            Self::Markdown => ".",
            Self::Css => ".",
            Self::Fish => ".",
            Self::Gdscript => ".",
            Self::Gdshader => ".",
            Self::GodotResource => ".",
            Self::ObjC => ".",
            Self::Perl => ".",
            Self::SvelteNext => ".",
            Self::Zsh => ".",
            Self::Sql => ".",
            Self::Yaml => ".",
            Self::Toml => ".",
            _ => "/",
        }
    }
}
